### ISSUE TITLE
Filename for saved spot location should not be csv as file is binary

### ISSUE THREAD

**Issue by feranick** [andim/easyleed#17]
Currently the saved spot locations are saved as binary data, but they use csv as the file extension. This should be changed to something else (pkl? or bin?) as csv has a clear meaning and it's confusing to the user

**Comment by andim** [comment]
Maybe it would be better to make this align the other way round? This is actually save the spot locations as csv.

**Comment by feranick** [comment]
Do you mean actually save this as csv? That can be done, but it will require some level of restructuring. For example: how do you want to save it? The read from csv will need to be rewritten too. 

Keeping it binary would be an easy fix (temporary or not, it will be more transparent to the user). besides, I don't see much value in having a clear text spot position per se, as it will always be used within easyleed.

My vote is to change the extension.

**Comment by andim** [comment]
One could use the extracted spot positions for postprocessing (external plotting of overlayed positions onto images, smoothing of the extracted spot positions, etc.). 

I agree about the change in filename being a valuable and much easier fix, so by all means make it a PR.

**Comment by feranick** [comment]
Closed #17 via #18
