### ISSUE TITLE
Give the possibility of manual freedom in intensity extraction without automation

### ISSUE THREAD

**Issue by andim** [andim/easyleed#4]
_From @feranick on October 4, 2014 20:48_

The idea is to to just extract the intensity without caring to much about automation. One could combine the Kalman filter with some manual intervention. The idea would simply be to let the user correct the predicted positions from time to time. The user input could then be incorporated into updating the state model in the same way that the guesses from the fitted positions currently are.

From private communication with Andi.

_Copied from original issue: feranick/easyleed#22_

**Comment by andim** [comment]
_From @feranick on October 9, 2014 23:27_

Consider also the possibility to add a "Pause" in the acquisition to allow for readjustments in spot positions.

**Comment by feranick** [comment]
This is implemented in #32. Closing.
