### ISSUE TITLE
Color coding for multiple beam selections

### ISSUE THREAD

**Issue by mgrady3** [andim/easyleed#7]
It would be nice if the UI for beam selections would color code the QGraphicsEllipseItems (or their subclass objects) to match the color used in the I(V) plot. If you select 4+ beams and all the circular selections are blue, it becomes difficult to distinguish which I(V) curve belongs to which beam since the curves are separated by colors.

**Comment by andim** [comment]
Agreed that this would be a useful addition. If you want to have it a go I would be happy about a PR.

**Comment by feranick** [comment]
This is addressed in #31. Closing. Please reopen if the adopted solution is not satisfactory.
