### ISSUE TITLE
Clear plots button doesn't actually clear plot

### ISSUE THREAD

**Issue by mgrady3** [andim/easyleed#8]
Your method in gui.py clearPlot() is not actually connected to the  QPuchButton titled Clear Plots

rather clearPlot() is only ever called from the method restart(). This is unintuitive.

Also: 
OS X 11.4 El Capitan, Python 3.5, PyQt5 via easyleed --pyqt5: clicking restart in the menu bar does not clear the plots, neither does clicking the clear plots push button.

I have tested a fix for the second issue:

in your clearPlot() method, change self.axes.cla() to self.axes.clear().

it might be that matplotlib is not registering your PlotWidget's axes as the 'current' axis. The cla() function documentation says that it clears the 'current' axes, which is somewhat ambiguous.

As for addressing the first issue, that would seemingly require a bit of refactoring.

**Comment by andim** [comment]
I have addressed the second part of the issue.

As for the first part maybe the easiest solution would be to remove the Clear Plot button. Is it ever useful to clear the plot without restarting the analysis?
