### ISSUE TITLE
Apply changes to preferences does not save into config

### ISSUE THREAD

**Issue by feranick** [andim/easyleed#9]
After I made changes to the preference panel, when I push apply, the new settings are available as long as I remain in the same session. If I close EasyLEED and reopen it, those settings are lost, as the were never saved back into defaultconfig.py

**Comment by andim** [comment]
This is the expected behavior currently. You need to explicitly save the parameter setting to a file in the widget and then load it again. This saving and loading of parameters seems broken currently, but I will try and fix it.

**Comment by andim** [comment]
Turns out addressing the issues with the parameter loading/saving was easy. The issue was simply to use binary mode for the file (see commit 2231fc1edd23a047ea1561f9125438fb12329078). You can try saving and loading your parameter values using the master version.

**Comment by feranick** [comment]
A much better approach is to use a Parser, which is a much cleaner implementation. No time for patch though :-)

**Comment by andim** [comment]
Yeah, a revamp of the whole parameter setting machinery would be nice. Also no time right now though.
